// 284 municípios brasileiros para SEO programático.
// Cobre as 27 capitais (presença em todos os estados) + grandes municípios por
// população (IBGE 2022) + cidades com polo real de Anhanguera/Unopar/Pitágoras
// (via API Tartarus). Manter sincronizado com next-sitemap.config.js.
// Ordem das primeiras 102: top por relevância/população (usado em internal linking).
export interface BrazilianCity {
  name: string
  state: string
  slug: string
}

function slugify(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

const RAW_CITIES: Array<[string, string]> = [
  ['São Paulo', 'SP'],
  ['Rio de Janeiro', 'RJ'],
  ['Brasília', 'DF'],
  ['Fortaleza', 'CE'],
  ['Salvador', 'BA'],
  ['Belo Horizonte', 'MG'],
  ['Manaus', 'AM'],
  ['Curitiba', 'PR'],
  ['Recife', 'PE'],
  ['Goiânia', 'GO'],
  ['Belém', 'PA'],
  ['Porto Alegre', 'RS'],
  ['Guarulhos', 'SP'],
  ['Campinas', 'SP'],
  ['São Luís', 'MA'],
  ['São Gonçalo', 'RJ'],
  ['Maceió', 'AL'],
  ['Duque de Caxias', 'RJ'],
  ['Campo Grande', 'MS'],
  ['Natal', 'RN'],
  ['Teresina', 'PI'],
  ['São Bernardo do Campo', 'SP'],
  ['Nova Iguaçu', 'RJ'],
  ['João Pessoa', 'PB'],
  ['Santo André', 'SP'],
  ['Osasco', 'SP'],
  ['Jaboatão dos Guararapes', 'PE'],
  ['São José dos Campos', 'SP'],
  ['Ribeirão Preto', 'SP'],
  ['Uberlândia', 'MG'],
  ['Sorocaba', 'SP'],
  ['Contagem', 'MG'],
  ['Aracaju', 'SE'],
  ['Feira de Santana', 'BA'],
  ['Cuiabá', 'MT'],
  ['Joinville', 'SC'],
  ['Juiz de Fora', 'MG'],
  ['Londrina', 'PR'],
  ['Aparecida de Goiânia', 'GO'],
  ['Ananindeua', 'PA'],
  ['Florianópolis', 'SC'],
  ['Niterói', 'RJ'],
  ['Serra', 'ES'],
  ['Belford Roxo', 'RJ'],
  ['Campos dos Goytacazes', 'RJ'],
  ['Caxias do Sul', 'RS'],
  ['Vila Velha', 'ES'],
  ['São João de Meriti', 'RJ'],
  ['Mauá', 'SP'],
  ['Carapicuíba', 'SP'],
  ['Mogi das Cruzes', 'SP'],
  ['Santos', 'SP'],
  ['Diadema', 'SP'],
  ['Olinda', 'PE'],
  ['Betim', 'MG'],
  ['Maringá', 'PR'],
  ['Jundiaí', 'SP'],
  ['Caucaia', 'CE'],
  ['Anápolis', 'GO'],
  ['Piracicaba', 'SP'],
  ['Itaquaquecetuba', 'SP'],
  ['Vitória', 'ES'],
  ['Montes Claros', 'MG'],
  ['São José do Rio Preto', 'SP'],
  ['Cariacica', 'ES'],
  ['Caruaru', 'PE'],
  ['Pelotas', 'RS'],
  ['Bauru', 'SP'],
  ['Canoas', 'RS'],
  ['Blumenau', 'SC'],
  ['Suzano', 'SP'],
  ['Vitória da Conquista', 'BA'],
  ['Ribeirão das Neves', 'MG'],
  ['Franca', 'SP'],
  ['Petrolina', 'PE'],
  ['Ponta Grossa', 'PR'],
  ['Paulista', 'PE'],
  ['Camaçari', 'BA'],
  ['Petrópolis', 'RJ'],
  ['Uberaba', 'MG'],
  ['Cascavel', 'PR'],
  ['Praia Grande', 'SP'],
  ['Taubaté', 'SP'],
  ['Limeira', 'SP'],
  ['Santa Maria', 'RS'],
  ['Gravataí', 'RS'],
  ['Mossoró', 'RN'],
  ['Volta Redonda', 'RJ'],
  ['Sumaré', 'SP'],
  ['Várzea Grande', 'MT'],
  ['Imperatriz', 'MA'],
  ['Foz do Iguaçu', 'PR'],
  ['São Vicente', 'SP'],
  ['Embu das Artes', 'SP'],
  ['Hortolândia', 'SP'],
  ['Marília', 'SP'],
  ['Indaiatuba', 'SP'],
  ['Porto Velho', 'RO'],
  ['Macapá', 'AP'],
  ['Rio Branco', 'AC'],
  ['Boa Vista', 'RR'],
  ['Palmas', 'TO'],
  ['Águas Lindas de Goiás', 'GO'],
  ['Alagoinhas', 'BA'],
  ['Alegrete', 'RS'],
  ['Alfenas', 'MG'],
  ['Almenara', 'MG'],
  ['Altamira', 'PA'],
  ['Alvorada', 'RS'],
  ['Americana', 'SP'],
  ['Angra dos Reis', 'RJ'],
  ['Apucarana', 'PR'],
  ['Aquidauana', 'MS'],
  ['Araçuaí', 'MG'],
  ['Arapiraca', 'AL'],
  ['Arapongas', 'PR'],
  ['Araranguá', 'SC'],
  ['Araraquara', 'SP'],
  ['Araruama', 'RJ'],
  ['Ariquemes', 'RO'],
  ['Assis', 'SP'],
  ['Atibaia', 'SP'],
  ['Bacabal', 'MA'],
  ['Bagé', 'RS'],
  ['Bandeirantes', 'PR'],
  ['Barra do Bugres', 'MT'],
  ['Barra do Corda', 'MA'],
  ['Barra do Garcas', 'MT'],
  ['Barra Mansa', 'RJ'],
  ['Barueri', 'SP'],
  ['Belo Jardim', 'PE'],
  ['Bom Jesus', 'PI'],
  ['Bom Jesus da Lapa', 'BA'],
  ['Botucatu', 'SP'],
  ['Bragança Paulista', 'SP'],
  ['Brumado', 'BA'],
  ['Cabo Frio', 'RJ'],
  ['Cachoeiro de Itapemirim', 'ES'],
  ['Caicó', 'RN'],
  ['Cajazeiras', 'PB'],
  ['Campina Grande', 'PB'],
  ['Canaa dos Carajas', 'PA'],
  ['Capanema', 'PA'],
  ['Capelinha', 'MG'],
  ['Castanhal', 'PA'],
  ['Catanduva', 'SP'],
  ['Caxias', 'MA'],
  ['Cerejeiras', 'RO'],
  ['Chapadao do Sul', 'MS'],
  ['Chapecó', 'SC'],
  ['Codó', 'MA'],
  ['Colatina', 'ES'],
  ['Colinas do Tocantins', 'TO'],
  ['Concordia', 'SC'],
  ['Corumba', 'MS'],
  ['Cotia', 'SP'],
  ['Coxim', 'MS'],
  ['Crato', 'CE'],
  ['Criciúma', 'SC'],
  ['Cruz Alta', 'RS'],
  ['Cruzeiro do Sul', 'AC'],
  ['Divinópolis', 'MG'],
  ['Dourados', 'MS'],
  ['Erechim', 'RS'],
  ['Esperantina', 'PI'],
  ['Eunapolis', 'BA'],
  ['Formosa do Rio Preto', 'BA'],
  ['Garanhuns', 'PE'],
  ['Governador Valadares', 'MG'],
  ['Gramado', 'RS'],
  ['Guanambi', 'BA'],
  ['Guarai', 'TO'],
  ['Guarapari', 'ES'],
  ['Guarapuava', 'PR'],
  ['Gurupi', 'TO'],
  ['Ilhéus', 'BA'],
  ['Ipatinga', 'MG'],
  ['Irece', 'BA'],
  ['Itabira', 'MG'],
  ['Itaboraí', 'RJ'],
  ['Itabuna', 'BA'],
  ['Itaituba', 'PA'],
  ['Itajaí', 'SC'],
  ['Itapecerica da Serra', 'SP'],
  ['Itapetinga', 'BA'],
  ['Itapetininga', 'SP'],
  ['Itapeva', 'SP'],
  ['Itapevi', 'SP'],
  ['Itapuranga', 'GO'],
  ['Itu', 'SP'],
  ['Itumbiara', 'GO'],
  ['Jacareí', 'SP'],
  ['Jacobina', 'BA'],
  ['Jaragua do Sul', 'SC'],
  ['Jau', 'SP'],
  ['Jequie', 'BA'],
  ['Juazeiro', 'BA'],
  ['Juazeiro do Norte', 'CE'],
  ['Lages', 'SC'],
  ['Lauro de Freitas', 'BA'],
  ['Leme', 'SP'],
  ['Linhares', 'ES'],
  ['Luis Eduardo Magalhaes', 'BA'],
  ['Luziânia', 'GO'],
  ['Macaé', 'RJ'],
  ['Magé', 'RJ'],
  ['Marabá', 'PA'],
  ['Maranguape', 'CE'],
  ['Marataizes', 'ES'],
  ['Marica', 'RJ'],
  ['Matao', 'SP'],
  ['Monte Alegre', 'RN'],
  ['Muriae', 'MG'],
  ['Nova Friburgo', 'RJ'],
  ['Novo Hamburgo', 'RS'],
  ['Palhoca', 'SC'],
  ['Para de Minas', 'MG'],
  ['Paragominas', 'PA'],
  ['Paraiso do Tocantins', 'TO'],
  ['Paranagua', 'PR'],
  ['Parauapebas', 'PA'],
  ['Parnaíba', 'PI'],
  ['Passo Fundo', 'RS'],
  ['Patos', 'PB'],
  ['Patos de Minas', 'MG'],
  ['Paulo Afonso', 'BA'],
  ['Penapolis', 'SP'],
  ['Picos', 'PI'],
  ['Pindamonhangaba', 'SP'],
  ['Piracuruca', 'PI'],
  ['Pirapora', 'MG'],
  ['Pirassununga', 'SP'],
  ['Pocos de Caldas', 'MG'],
  ['Ponta Pora', 'MS'],
  ['Ponte Nova', 'MG'],
  ['Portao', 'RS'],
  ['Porto Nacional', 'TO'],
  ['Pouso Alegre', 'MG'],
  ['Presidente Dutra', 'MA'],
  ['Presidente Prudente', 'SP'],
  ['Primavera do Leste', 'MT'],
  ['Redencao', 'PA'],
  ['Resende', 'RJ'],
  ['Rio Claro', 'SP'],
  ['Rio Grande', 'RS'],
  ['Rio Verde', 'GO'],
  ['Rondonópolis', 'MT'],
  ['Santa Barbara D\'oeste', 'SP'],
  ['Santa Luzia', 'MG'],
  ['Santa Vitoria do Palmar', 'RS'],
  ['Santarém', 'PA'],
  ['Santo Antonio de Jesus', 'BA'],
  ['São Borja', 'RS'],
  ['São Caetano do Sul', 'SP'],
  ['São Carlos', 'SP'],
  ['São Francisco', 'MG'],
  ['São José', 'SC'],
  ['São Leopoldo', 'RS'],
  ['São Mateus', 'ES'],
  ['Sapucaia do Sul', 'RS'],
  ['Sarandi', 'PR'],
  ['Seabra', 'BA'],
  ['Senador Canedo', 'GO'],
  ['Sertaozinho', 'SP'],
  ['Sete Lagoas', 'MG'],
  ['Sinop', 'MT'],
  ['Sobral', 'CE'],
  ['Sorriso', 'MT'],
  ['Taboao da Serra', 'SP'],
  ['Tangara da Serra', 'MT'],
  ['Teixeira de Freitas', 'BA'],
  ['Teresópolis', 'RJ'],
  ['Timon', 'MA'],
  ['Toledo', 'PR'],
  ['Tubarão', 'SC'],
  ['Tucuruí', 'PA'],
  ['Umuarama', 'PR'],
  ['Uruguaiana', 'RS'],
  ['Vacaria', 'RS'],
  ['Valinhos', 'SP'],
  ['Valparaiso de Goias', 'GO'],
  ['Varginha', 'MG'],
  ['Vilhena', 'RO'],
  ['Vitória de Santo Antão', 'PE'],
]

export const BRAZILIAN_CITIES: BrazilianCity[] = RAW_CITIES.map(([name, state]) => ({
  name,
  state,
  slug: slugify(name),
}))

export function getCityBySlug(slug: string): BrazilianCity | undefined {
  return BRAZILIAN_CITIES.find(city => city.slug === slug)
}

export function getAllCitySlugs(): string[] {
  return BRAZILIAN_CITIES.map(city => city.slug)
}

// Subset usado em internal linking quando 100+ cards seria excessivo no UI.
export function getTopCities(limit: number = 30): BrazilianCity[] {
  return BRAZILIAN_CITIES.slice(0, limit)
}
