/* eslint-disable @typescript-eslint/no-explicit-any */
export const studentData = (data: any, offerData: any) => ({
  dadosPessoais: {
    nome: data.name,
    rg: '40000000',
    sexo: data.gender === 'masculino' ? 'M' : 'F',
    cpf: data.cpf,
    celular: data.phone,
    dataNascimento: data.birthDate,
    email: data.email,
    necessidadesEspeciais: [],
    endereco: {
      bairro: data.neighbordhood,
      cep: data.cep,
      complemento: '',
      logradouro: data.address,
      municipio: data.city,
      numero: parseInt(data.addressNumber, 10),
      uf: data.state,
    },
  },
  inscricao: {
    aceiteTermo: true,
    anoConclusao: parseInt(data.schoolYear, 10),
    enem: {
      isUsed: false,
    },
    receberEmail: true,
    receberSMS: true,
    receberWhatsApp: data.whatsapp,
    courseOffer: {
      offerId: offerData.offerId,
      offerBusinessKey: offerData.offerBusinessKey,
      shift: '*',
      subscriptionValue: String(offerData.subscriptionValue || '99'),
      montlyFeeFrom: String(offerData.montlyFeeFrom || '99'),
      montlyFeeTo: String(offerData.montlyFeeTo || '99'),
      expiredAt: offerData.expiredAt,
      weekday: offerData.weekday,
      classTimeStart: offerData.classTimeStart,
      classTimeEnd: offerData.classTimeEnd,
      brand: offerData.brand,
      course: offerData.course,
      courseId: offerData.courseId,
      unit: offerData.unit,
      unitId: offerData.unitId,
      unitAddress: offerData.unitAddress,
      unitCity: offerData.unitCity,
      unitState: offerData.unitState,
      modality: offerData.modality,
      viewShift: 'false',
      lateEnrollment: true,
      cityId: '',
      stateId: '',
      degree: 'UNDERGRADUATE',
      promoter: process.env.ID_PROMOTER as string,
      id: offerData.offerId,
      type: 'UNDERGRADUATE',
    },
  },
  promoterId: process.env.ID_PROMOTER as string,
  idSalesChannel: 88,
  canal: 'web',
})
